# Generated by Django 5.2.16 on 2026-07-15 20:25

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('report', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_auditrun',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('live_fetch', 'Live fetch'), ('bulk_import', 'Bulk import'), ('history_replay', 'History replay'), ('legacy_baseline', 'Legacy baseline'), ('manual', 'Manual')], db_index=True, default='bulk_import', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('max_ads', models.IntegerField(blank=True, null=True)),
                ('page_pause', models.FloatField(blank=True, null=True)),
                ('fetched_count', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('price_change_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_fetchrun',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('live_fetch', 'Live fetch'), ('bulk_import', 'Bulk import'), ('history_replay', 'History replay'), ('legacy_baseline', 'Legacy baseline')], default='bulk_import', max_length=32)),
                ('first_observed_at', models.DateTimeField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.ad')),
            ],
            options={
                'db_table': 'history_adversion',
                'ordering': ('first_observed_at',),
            },
        ),
        migrations.CreateModel(
            name='AdObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('raw_hash', models.CharField(max_length=64)),
                ('publish_phrase', models.CharField(blank=True, max_length=120)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='catalog.ad')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='history.adversion')),
                ('fetch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='history.fetchrun')),
            ],
            options={
                'db_table': 'history_adobservation',
                'ordering': ('observed_at',),
            },
        ),
        migrations.CreateModel(
            name='AdChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('content_changed', 'Content changed'), ('route_changed', 'Route changed'), ('reappeared', 'Reappeared')], max_length=24)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('changed_paths', models.JSONField(blank=True, default=list)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('origin', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='catalog.ad')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='history.adobservation')),
                ('new_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_as_new', to='history.adversion')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_as_prev', to='history.adversion')),
            ],
            options={
                'db_table': 'history_adchangeevent',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UnknownTimePhrase',
            fields=[
                ('phrase', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('seen_count', models.IntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('first_fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_unknown_phrases', to='history.fetchrun')),
                ('last_fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_unknown_phrases', to='history.fetchrun')),
            ],
            options={
                'db_table': 'history_unknownphrase',
            },
        ),
        migrations.AddConstraint(
            model_name='adversion',
            constraint=models.UniqueConstraint(fields=('ad', 'semantic_hash'), name='uq_adversion_ad_semantic'),
        ),
        migrations.AddIndex(
            model_name='adchangeevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['categories'], name='change_cat_gin'),
        ),
        migrations.AddIndex(
            model_name='adchangeevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['changed_paths'], name='change_paths_gin'),
        ),
        migrations.AddConstraint(
            model_name='adchangeevent',
            constraint=models.UniqueConstraint(fields=('observation', 'event_type'), name='uq_change_obs_type'),
        ),
        migrations.AddIndex(
            model_name='adobservation',
            index=models.Index(fields=['ad', 'observed_at'], name='obs_ad_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='adobservation',
            constraint=models.UniqueConstraint(fields=('fetch_run', 'ad'), name='uq_observation_run_ad'),
        ),
    ]
