# Generated by Django 5.2.16 on 2026-07-15 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_cache',
            },
        ),
        migrations.CreateModel(
            name='PriceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('time_window', models.CharField(default='all', max_length=16)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('min_price', models.BigIntegerField(blank=True, null=True)),
                ('max_price', models.BigIntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='catalog.brand')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='catalog.model')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='catalog.variant')),
            ],
            options={
                'db_table': 'analytics_pricestatistics',
                'ordering': ('brand', 'model', 'variant', 'year'),
                'constraints': [models.UniqueConstraint(fields=('brand', 'model', 'variant', 'year', 'time_window'), name='uq_stats_market_window')],
            },
        ),
    ]
