# Generated by Django 5.2.16 on 2026-07-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('catalog', '0003_ad_removed_at_ad_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('ad_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('median_price', models.BigIntegerField(blank=True, null=True)),
                ('mean_price', models.BigIntegerField(blank=True, null=True)),
                ('min_price', models.BigIntegerField(blank=True, null=True)),
                ('max_price', models.BigIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_snapshots', to='catalog.model')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_snapshots', to='catalog.variant')),
            ],
            options={
                'db_table': 'analytics_dailyinventorysnapshot',
                'ordering': ('-date', 'model'),
                'indexes': [models.Index(fields=['model', 'date'], name='snap_model_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('model', 'variant', 'year', 'date'), name='uq_snapshot_market_date')],
            },
        ),
    ]
