# Generated by Django 5.2.16 on 2026-07-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dailyinventorysnapshot'),
        ('catalog', '0003_ad_removed_at_ad_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('removed_count', models.IntegerField(default=0)),
                ('median_price', models.BigIntegerField(blank=True, null=True)),
                ('mean_price', models.BigIntegerField(blank=True, null=True)),
                ('min_price', models.BigIntegerField(blank=True, null=True)),
                ('max_price', models.BigIntegerField(blank=True, null=True)),
                ('brand_breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_marketsnapshot',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='DealScoreCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('discount_pct', models.FloatField(blank=True, null=True)),
                ('peer_median', models.BigIntegerField(blank=True, null=True)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_score', to='catalog.ad')),
            ],
            options={
                'db_table': 'analytics_dealscorecache',
                'ordering': ('-score',),
            },
        ),
    ]
