# Generated by Django 5.2.16 on 2026-07-15 20:25

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('slug', models.SlugField(max_length=120, primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=120, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=120, null=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'catalog_brand',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=120, unique=True)),
                ('province', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'catalog_city',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('package_type', models.CharField(blank=True, max_length=64)),
                ('score', models.FloatField(blank=True, null=True)),
                ('ad_count', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('logo', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'catalog_dealer',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=160)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.brand')),
            ],
            options={
                'db_table': 'catalog_model',
                'ordering': ('brand__name_fa', 'name_fa'),
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(default='default', max_length=200)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.model')),
            ],
            options={
                'db_table': 'catalog_variant',
                'ordering': ('model__name_fa', 'name_fa'),
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('mileage', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120)),
                ('transmission', models.CharField(blank=True, db_index=True, max_length=64)),
                ('current_price', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('current_payment', models.BigIntegerField(blank=True, null=True)),
                ('current_prepayment', models.BigIntegerField(blank=True, null=True)),
                ('current_installments', models.IntegerField(blank=True, null=True)),
                ('price_type', models.CharField(blank=True, max_length=64)),
                ('publish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('publish_phrase', models.CharField(blank=True, max_length=120)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trim', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('body_type', models.CharField(blank=True, max_length=120)),
                ('body_color', models.CharField(blank=True, max_length=120)),
                ('body_status', models.CharField(blank=True, max_length=120)),
                ('fuel', models.CharField(blank=True, max_length=64)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('canonical_path', models.CharField(blank=True, max_length=400)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='catalog.brand')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='catalog.city')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='catalog.dealer')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='catalog.model')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='catalog.variant')),
            ],
            options={
                'db_table': 'catalog_ad',
                'ordering': ('-publish_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('brand', 'name_fa'), name='uq_model_brand_name'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('model', 'name_fa'), name='uq_variant_model_name'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['model', 'variant', 'year'], name='ad_market_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['model', 'current_price'], name='ad_market_price_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=django.contrib.postgres.indexes.GinIndex(fields=['raw_payload'], name='ad_raw_gin', opclasses=['jsonb_path_ops']),
        ),
    ]
