# Generated by Django 5.2.16 on 2026-07-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=160, primary_key=True, serialize=False),
        ),
    ]
