# Generated by Django 5.2.16 on 2026-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed (not seen within STALE_AFTER_DAYS)')], db_index=True, default='active', max_length=16),
        ),
    ]
