# Generated by Django 5.2.16 on 2026-08-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_frontend_rebuild"),
    ]

    operations = [
        migrations.RemoveField(model_name="alert", name="saved_search"),
        migrations.RemoveField(model_name="alert", name="watchlist"),
        migrations.DeleteModel(name="SavedSearch"),
        migrations.DeleteModel(name="Watchlist"),
    ]
