# Generated by Django 5.2.16 on 2026-08-13 15:25

import django.db.models.deletion
from django.db import migrations, models


def keep_earliest_favorite_per_ad(apps, schema_editor):
    """One operator, one saved list: keep the earliest Favorite row per ad."""
    Favorite = apps.get_model("accounts", "Favorite")
    keep = []
    seen = set()
    for pk, ad_id in Favorite.objects.order_by("created_at", "id").values_list(
        "id", "ad_id"
    ):
        if ad_id in seen:
            continue
        seen.add(ad_id)
        keep.append(pk)
    if keep:
        Favorite.objects.exclude(pk__in=keep).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_drop_watchlists_saved_searches'),
        ('core', '0016_drop_identity_and_quality_snapshot'),
    ]

    operations = [
        migrations.RunPython(keep_earliest_favorite_per_ad, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='alert',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='model',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='featureusagecounter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_ad',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proaccessrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='proaccessrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffauditlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='uq_favorite_user_ad',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deletion_requested_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_completed_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_brands',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_models',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_version',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='core.ad'),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='FeatureUsageCounter',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ProAccessRequest',
        ),
        migrations.DeleteModel(
            name='ProductEvent',
        ),
        migrations.DeleteModel(
            name='StaffAuditLog',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
