# Generated by Django 5.2.16 on 2026-08-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_owned_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_demo',
        ),
    ]
