# Generated by Django 5.2.17 on 2026-08-31 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_drop_is_demo'),
        ('core', '0027_alter_marketindex_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_slug', models.CharField(blank=True, max_length=160)),
                ('year_jalali', models.IntegerField(blank=True, null=True)),
                ('scope_key', models.CharField(db_index=True, editable=False, max_length=200)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('min_discount_pct', models.FloatField(default=10.0)),
                ('min_peers', models.IntegerField(default=8)),
                ('price_min', models.BigIntegerField(blank=True, null=True)),
                ('price_max', models.BigIntegerField(blank=True, null=True)),
                ('mileage_max', models.BigIntegerField(blank=True, null=True)),
                ('exclude_review', models.BooleanField(default=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.variant')),
            ],
            options={
                'db_table': 'accounts_alertrule',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_pct', models.FloatField(blank=True, null=True)),
                ('peer_median', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='accounts.alertrule')),
            ],
            options={
                'db_table': 'accounts_alertdelivery',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_slug', models.CharField(blank=True, max_length=160)),
                ('year_jalali', models.IntegerField(blank=True, null=True)),
                ('scope_key', models.CharField(db_index=True, editable=False, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.variant')),
            ],
            options={
                'db_table': 'accounts_watchlist',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['user', 'enabled'], name='alertrule_user_on_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['user', 'read_at'], name='alert_user_unread_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertdelivery',
            constraint=models.UniqueConstraint(fields=('user', 'ad'), name='uq_alert_user_ad'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'scope_key'), name='uq_watchlist_user_scope'),
        ),
    ]
