# Generated by Django 5.2 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alertrule_alertdelivery_watchlist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="min_residual_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertdelivery",
            name="residual_pct",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
