/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/ads/{code}/provenance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Raw provenance for one ad: the stored payload and every version's payload. Operator-only — this is the whole scraped record, which is why it is no longer part of the public ad serializer. */
        get: operations["admin_ads_provenance_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Database size, catalog counts, recent ingest rejects, crawl checks. */
        get: operations["admin_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/crawl-health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Crawl health: sweep freshness, failed runs, ingest-reject spikes, coverage gaps, ingest progress. Read-only. Operator-only. */
        get: operations["admin_jobs_crawl_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/deal-scores/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Rebuild per-ad DealScoreCache (the best-deal board). Operator-only. */
        post: operations["admin_jobs_deal_scores_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/fetch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Trigger an async live Bama fetch (operator-only). */
        post: operations["admin_jobs_fetch_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Recent scheduled-job outcomes, newest first, including skips. */
        get: operations["admin_jobs_overview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/refresh-analytics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Rebuild every derived analytic — snapshots, market index, deal scores — without fetching. Operator-only. */
        post: operations["admin_jobs_refresh_analytics_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/ads/ and GET /api/ads/<code>/.
         *
         *     The default list queryset is restricted to publish-complete ads (those with
         *     a `publish_at` and a strictly positive `current_price`) and drops rows the
         *     cohort pass flagged as priced far ABOVE their peers — ?include_outliers=true
         *     restores them. Suspiciously cheap listings are never hidden.
         */
        get: operations["ads_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/ads/ and GET /api/ads/<code>/.
         *
         *     The default list queryset is restricted to publish-complete ads (those with
         *     a `publish_at` and a strictly positive `current_price`) and drops rows the
         *     cohort pass flagged as priced far ABOVE their peers — ?include_outliers=true
         *     restores them. Suspiciously cheap listings are never hidden.
         */
        get: operations["ads_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/{code}/fair-price/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Explainable fair-price estimate for one listing, with components. */
        get: operations["ads_fair_price_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ads/{code}/price-history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Single ad's change-only price series over time. */
        get: operations["ads_price_history_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/deal-scores/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Deal scores, joined to ad. Filtered, ordered by discount, paginated.
         *
         *     Returns ``count`` alongside ``results`` so the board can page: the cache
         *     holds ~9,800 rows and the screen used to show a hard-coded top 50 with no
         *     way forward, which put every genuine 5–20% deal out of reach.
         */
        get: operations["analytics_deal_scores_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/deal-scores/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Single ad's deal score or 404. */
        get: operations["analytics_deal_score_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/market-index/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Composition-controlled price index (base 100).
         *
         *     Unlike the raw median, this cannot move because the mix of listings changed
         *     — only because prices within a cohort changed. See
         *     ``apps/core/services/index.py``.
         */
        get: operations["analytics_market_index_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Market summary: size, freshness and how much is verifiable. */
        get: operations["analytics_overview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brands/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/brands/ and GET /api/brands/<slug>/. */
        get: operations["brands_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brands/{brand_slug}/models/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/brands/<slug>/models/ — list models for a brand (by name_fa). */
        get: operations["brands_models_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brands/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/brands/ and GET /api/brands/<slug>/. */
        get: operations["brands_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Saved ads. POST {code}; idempotent if already saved. */
        get: operations["favorites_list"];
        put?: never;
        /** @description Saved ads. POST {code}; idempotent if already saved. */
        post: operations["favorites_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Saved ads. POST {code}; idempotent if already saved. */
        get: operations["favorites_retrieve"];
        put?: never;
        post?: never;
        /** @description Saved ads. POST {code}; idempotent if already saved. */
        delete: operations["favorites_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Landing: per-model market summary (publish-complete, priced), top-N.
         *
         *     Reports the **median**, not the mean. Asking prices on this feed are heavily
         *     right-skewed and a handful of typo listings (a Peugeot 206 at 5.8 trillion
         *     toman) dragged the mean to roughly twice the median, so the headline number
         *     described no car actually on the market. Medians are computed in Python:
         *     there is no portable ORM median aggregate, the input is one narrow
         *     two-column scan, and the response is cached for two minutes.
         */
        get: operations["markets_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_pk}/variants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/models/<pk>/variants/ — list variants for a model. */
        get: operations["models_variants_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifier-settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get or update the deal-notifier thresholds and scope. */
        get: operations["notifier_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Get or update the deal-notifier thresholds and scope. */
        patch: operations["notifier_settings_partial_update"];
        trace?: never;
    };
    "/api/research/depreciation/{model_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Median asking price by model year, and retention against the newest. */
        get: operations["research_depreciation_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/liquidity/{model_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Time-to-delist for a cohort, using Kaplan-Meier so listings that are still live are censored rather than dropped. Never described as 'sold': the feed cannot distinguish a sale from an expiry or a withdrawal. */
        get: operations["research_liquidity_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Flat current-snapshot of an ad.
         *
         *     Brand is referenced by its natural value (slug); model/variant/city/dealer
         *     by id. `raw_payload` is exposed verbatim as nested JSON (read-only).
         */
        Ad: {
            code: string;
            readonly brand_slug: string;
            readonly brand_name: string;
            readonly model_id: number;
            /** @default  */
            readonly model_name: string;
            readonly variant_id: number;
            /** @default  */
            readonly variant_name: string;
            year?: number | null;
            /** Format: int64 */
            mileage?: number | null;
            /** Format: int64 */
            current_price?: number | null;
            price_type?: string;
            /** Format: date-time */
            publish_at?: string | null;
            /** Format: date-time */
            last_seen_at?: string | null;
            title?: string;
            transmission?: string;
            body_type?: string;
            fuel?: string;
            readonly city_id: number;
            /** @default  */
            readonly city_name: string;
            url?: string;
            description?: string;
            primary_image_url?: string;
            image_urls?: unknown;
            image_count?: number | null;
            seller_authenticated?: boolean | null;
            readonly dealer_name: string;
            readonly seller_type: string;
            year_jalali?: number | null;
            status?: components["schemas"]["StatusEnum"];
            readonly cohort_flags: unknown;
            readonly price_basis_unclear: boolean;
            readonly condition_flagged: boolean;
        };
        Brand: {
            slug: string;
            name_fa: string;
            name_en?: string | null;
            aliases?: unknown;
        };
        Favorite: {
            code: string;
            readonly ad_title: string;
            readonly ad_price: number;
            readonly previous_price: number | null;
            /** Format: date-time */
            readonly price_changed_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        FavoriteRequest: {
            code: string;
        };
        /** @description 202 response body for an async admin job trigger. */
        JobAccepted: {
            status: string;
            command: string;
            poll?: string;
        };
        Model: {
            readonly id: number;
            readonly brand_slug: string;
            name_fa: string;
        };
        NotifierSettings: {
            enabled?: boolean;
            /** Format: double */
            min_discount_pct?: number;
            min_peers?: number;
            /** Format: int64 */
            price_min?: number | null;
            /** Format: int64 */
            price_max?: number | null;
            model_ids?: unknown;
            telegram_chat_id?: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PaginatedAdList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Ad"][];
        };
        PaginatedFavoriteList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Favorite"][];
        };
        PatchedNotifierSettingsRequest: {
            enabled?: boolean;
            /** Format: double */
            min_discount_pct?: number;
            min_peers?: number;
            /** Format: int64 */
            price_min?: number | null;
            /** Format: int64 */
            price_max?: number | null;
            model_ids?: unknown;
            telegram_chat_id?: string;
        };
        /**
         * @description * `active` - Active
         *     * `removed` - Removed (absent from the last completed sweeps)
         * @enum {string}
         */
        StatusEnum: "active" | "removed";
        Variant: {
            readonly id: number;
            readonly model_id: number;
            name_fa?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_ads_provenance_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    admin_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    admin_jobs_crawl_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All checks passed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description At least one check failed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_jobs_deal_scores_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
        };
    };
    admin_jobs_fetch_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description No response body */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_jobs_overview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    admin_jobs_refresh_analytics_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
        };
    };
    ads_list: {
        parameters: {
            query?: {
                body_type?: string;
                brand?: string;
                city?: number;
                fuel?: string;
                has_image?: boolean;
                last_seen_from?: string;
                mileage_max?: number;
                mileage_min?: number;
                model?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                price_max?: number;
                price_min?: number;
                publish_from?: string;
                q?: string;
                seller_authenticated?: boolean;
                /**
                 * @description * `dealer` - dealer
                 *     * `private` - private
                 */
                seller_type?: "dealer" | "private";
                status?: string;
                transmission?: string;
                variant?: number;
                year_max?: number;
                year_min?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdList"];
                };
            };
        };
    };
    ads_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this ad. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ad"];
                };
            };
        };
    };
    ads_fair_price_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ads_price_history_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    analytics_deal_scores_list: {
        parameters: {
            query?: {
                brand?: string;
                confidence?: "high" | "low" | "medium";
                limit?: number;
                /** @description Upper bound on discount %. The UI defaults to 30 — above that the gap is dominated by attributes the cohort cannot see (damage, pre-sale, bait). */
                max_score?: number;
                min_score?: number;
                model?: number;
                offset?: number;
                price_max?: number;
                price_min?: number;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    analytics_deal_score_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    analytics_market_index_retrieve: {
        parameters: {
            query?: {
                days?: number;
                /** @description Brand slug or model id; omit for scope=market. */
                id?: string;
                scope?: "brand" | "market" | "model";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    analytics_overview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    brands_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"][];
                };
            };
        };
    };
    brands_models_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path: {
                brand_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"][];
                };
            };
        };
    };
    brands_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this brand. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
        };
    };
    favorites_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFavoriteList"];
                };
            };
        };
    };
    favorites_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FavoriteRequest"];
                "multipart/form-data": components["schemas"]["FavoriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorite"];
                };
            };
        };
    };
    favorites_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this favorite. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorite"];
                };
            };
        };
    };
    favorites_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique value identifying this favorite. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markets_retrieve: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    models_variants_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
            };
            header?: never;
            path: {
                model_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Variant"][];
                };
            };
        };
    };
    notifier_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifierSettings"];
                };
            };
        };
    };
    notifier_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNotifierSettingsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNotifierSettingsRequest"];
                "multipart/form-data": components["schemas"]["PatchedNotifierSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifierSettings"];
                };
            };
        };
    };
    research_depreciation_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    research_liquidity_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
