# Generated by Django 5.2.16 on 2026-07-20 14:46

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('mileage', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120)),
                ('transmission', models.CharField(blank=True, db_index=True, max_length=64)),
                ('current_price', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('current_payment', models.BigIntegerField(blank=True, null=True)),
                ('current_prepayment', models.BigIntegerField(blank=True, null=True)),
                ('current_installments', models.IntegerField(blank=True, null=True)),
                ('price_type', models.CharField(blank=True, max_length=64)),
                ('publish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('publish_phrase', models.CharField(blank=True, max_length=120)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed (not seen within STALE_AFTER_DAYS)')], db_index=True, default='active', max_length=16)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('trim', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('body_type', models.CharField(blank=True, max_length=120)),
                ('body_color', models.CharField(blank=True, max_length=120)),
                ('body_status', models.CharField(blank=True, max_length=120)),
                ('fuel', models.CharField(blank=True, max_length=64)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('canonical_path', models.CharField(blank=True, max_length=400)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_ad',
                'ordering': ('-publish_at',),
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_cache',
            },
        ),
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('report', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_auditrun',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('slug', models.SlugField(allow_unicode=True, max_length=160, primary_key=True, serialize=False)),
                ('name_fa', models.CharField(max_length=120, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=120, null=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'catalog_brand',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=120, unique=True)),
                ('province', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'catalog_city',
                'ordering': ('name_fa',),
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('package_type', models.CharField(blank=True, max_length=64)),
                ('score', models.FloatField(blank=True, null=True)),
                ('ad_count', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('logo', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'catalog_dealer',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('live_fetch', 'Live fetch'), ('bulk_import', 'Bulk import'), ('history_replay', 'History replay'), ('legacy_baseline', 'Legacy baseline'), ('manual', 'Manual')], db_index=True, default='bulk_import', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('max_ads', models.IntegerField(blank=True, null=True)),
                ('page_pause', models.FloatField(blank=True, null=True)),
                ('fetched_count', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('price_change_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_fetchrun',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('active_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('removed_count', models.IntegerField(default=0)),
                ('median_price', models.BigIntegerField(blank=True, null=True)),
                ('mean_price', models.BigIntegerField(blank=True, null=True)),
                ('min_price', models.BigIntegerField(blank=True, null=True)),
                ('max_price', models.BigIntegerField(blank=True, null=True)),
                ('brand_breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_marketsnapshot',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='AdVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('live_fetch', 'Live fetch'), ('bulk_import', 'Bulk import'), ('history_replay', 'History replay'), ('legacy_baseline', 'Legacy baseline')], default='bulk_import', max_length=32)),
                ('first_observed_at', models.DateTimeField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.ad')),
            ],
            options={
                'db_table': 'history_adversion',
                'ordering': ('first_observed_at',),
            },
        ),
        migrations.CreateModel(
            name='AdObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('raw_hash', models.CharField(max_length=64)),
                ('publish_phrase', models.CharField(blank=True, max_length=120)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.ad')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.adversion')),
                ('fetch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.fetchrun')),
            ],
            options={
                'db_table': 'history_adobservation',
                'ordering': ('observed_at',),
            },
        ),
        migrations.CreateModel(
            name='AdChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('content_changed', 'Content changed'), ('route_changed', 'Route changed'), ('reappeared', 'Reappeared')], max_length=24)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('changed_paths', models.JSONField(blank=True, default=list)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('origin', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='core.ad')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='core.adobservation')),
                ('new_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_as_new', to='core.adversion')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_as_prev', to='core.adversion')),
            ],
            options={
                'db_table': 'history_adchangeevent',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='core.brand'),
        ),
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='core.city'),
        ),
        migrations.AddField(
            model_name='ad',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='core.dealer'),
        ),
        migrations.CreateModel(
            name='DealScoreCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('discount_pct', models.FloatField(blank=True, null=True)),
                ('peer_median', models.BigIntegerField(blank=True, null=True)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_score', to='core.ad')),
            ],
            options={
                'db_table': 'analytics_dealscorecache',
                'ordering': ('-score',),
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=160)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.brand')),
            ],
            options={
                'db_table': 'catalog_model',
                'ordering': ('brand__name_fa', 'name_fa'),
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='core.model'),
        ),
        migrations.CreateModel(
            name='PriceDropEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.BigIntegerField(blank=True, null=True)),
                ('new_price', models.BigIntegerField(blank=True, null=True)),
                ('drop_amount', models.BigIntegerField(db_index=True, default=0)),
                ('drop_pct', models.FloatField(db_index=True, default=0.0)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_drops', to='core.ad')),
            ],
            options={
                'db_table': 'market_pricedropevent',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('payment', models.BigIntegerField(blank=True, null=True)),
                ('prepayment', models.BigIntegerField(blank=True, null=True)),
                ('installments', models.IntegerField(blank=True, null=True)),
                ('price_type', models.CharField(blank=True, max_length=64)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='core.ad')),
                ('fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='core.fetchrun')),
            ],
            options={
                'db_table': 'market_priceobservation',
                'ordering': ('observed_at',),
            },
        ),
        migrations.CreateModel(
            name='UnknownTimePhrase',
            fields=[
                ('phrase', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('seen_count', models.IntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('first_fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_unknown_phrases', to='core.fetchrun')),
                ('last_fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_unknown_phrases', to='core.fetchrun')),
            ],
            options={
                'db_table': 'history_unknownphrase',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(default='default', max_length=200)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.model')),
            ],
            options={
                'db_table': 'catalog_variant',
                'ordering': ('model__name_fa', 'name_fa'),
            },
        ),
        migrations.CreateModel(
            name='PriceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('time_window', models.CharField(default='all', max_length=16)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('min_price', models.BigIntegerField(blank=True, null=True)),
                ('max_price', models.BigIntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='core.brand')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='core.model')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='core.variant')),
            ],
            options={
                'db_table': 'analytics_pricestatistics',
                'ordering': ('brand', 'model', 'variant', 'year'),
            },
        ),
        migrations.CreateModel(
            name='DailyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('ad_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('median_price', models.BigIntegerField(blank=True, null=True)),
                ('mean_price', models.BigIntegerField(blank=True, null=True)),
                ('min_price', models.BigIntegerField(blank=True, null=True)),
                ('max_price', models.BigIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_snapshots', to='core.model')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_snapshots', to='core.variant')),
            ],
            options={
                'db_table': 'analytics_dailyinventorysnapshot',
                'ordering': ('-date', 'model'),
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='core.variant'),
        ),
        migrations.AddConstraint(
            model_name='adversion',
            constraint=models.UniqueConstraint(fields=('ad', 'semantic_hash'), name='uq_adversion_ad_semantic'),
        ),
        migrations.AddIndex(
            model_name='adchangeevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['categories'], name='change_cat_gin'),
        ),
        migrations.AddIndex(
            model_name='adchangeevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['changed_paths'], name='change_paths_gin'),
        ),
        migrations.AddConstraint(
            model_name='adchangeevent',
            constraint=models.UniqueConstraint(fields=('observation', 'event_type'), name='uq_change_obs_type'),
        ),
        migrations.AddIndex(
            model_name='adobservation',
            index=models.Index(fields=['ad', 'observed_at'], name='obs_ad_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='adobservation',
            constraint=models.UniqueConstraint(fields=('fetch_run', 'ad'), name='uq_observation_run_ad'),
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('brand', 'name_fa'), name='uq_model_brand_name'),
        ),
        migrations.AddIndex(
            model_name='pricedropevent',
            index=models.Index(fields=['ad', '-observed_at'], name='pde_ad_time_idx'),
        ),
        migrations.AddIndex(
            model_name='pricedropevent',
            index=models.Index(fields=['-drop_pct'], name='pde_drop_pct_idx'),
        ),
        migrations.AddIndex(
            model_name='priceobservation',
            index=models.Index(fields=['ad', 'observed_at'], name='po_ad_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('model', 'name_fa'), name='uq_variant_model_name'),
        ),
        migrations.AddConstraint(
            model_name='pricestatistics',
            constraint=models.UniqueConstraint(fields=('brand', 'model', 'variant', 'year', 'time_window'), name='uq_stats_market_window'),
        ),
        migrations.AddIndex(
            model_name='dailyinventorysnapshot',
            index=models.Index(fields=['model', 'date'], name='snap_model_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyinventorysnapshot',
            constraint=models.UniqueConstraint(fields=('model', 'variant', 'year', 'date'), name='uq_snapshot_market_date'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['model', 'variant', 'year'], name='ad_market_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['model', 'current_price'], name='ad_market_price_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=django.contrib.postgres.indexes.GinIndex(fields=['raw_payload'], name='ad_raw_gin', opclasses=['jsonb_path_ops']),
        ),
    ]
