# Generated by Django 5.2.16 on 2026-07-26 09:39

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=16)),
                ('rule', models.CharField(db_index=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'history_ingestreject',
                'ordering': ('-observed_at',),
            },
        ),
        migrations.CreateModel(
            name='PageCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.IntegerField()),
                ('rank_lo', models.IntegerField()),
                ('rank_hi', models.IntegerField()),
                ('ad_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('changed_count', models.IntegerField(default=0)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'history_pagecoverage',
                'ordering': ('fetch_run', 'page_index'),
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='quality_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ad',
            name='year_calendar',
            field=models.CharField(blank=True, choices=[('jalali', 'Jalali'), ('gregorian', 'Gregorian'), ('unknown', 'Unknown')], max_length=16),
        ),
        migrations.AddField(
            model_name='ad',
            name='year_gregorian',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='year_jalali',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='deepest_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='mode',
            field=models.CharField(choices=[('delta', 'Delta (shallow, early-stopping)'), ('full', 'Full sweep (page 0 to end of feed)'), ('backfill', 'Backfill (explicit page range)')], db_index=True, default='delta', max_length=16),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='pages_fetched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='reached_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='resume_from_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='start_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='stop_reason',
            field=models.CharField(blank=True, choices=[('end_of_feed', 'Reached the empty page past the last ad'), ('stale_pages', 'Consecutive pages with nothing new'), ('max_ads', 'Hit the max_ads cap'), ('max_pages', 'Hit the page-range end (backfill)'), ('error', 'Aborted on an unrecoverable error'), ('interrupted', 'Interrupted by the operator')], max_length=24),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['model', 'variant', 'year_jalali'], name='ad_market_jy_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=django.contrib.postgres.indexes.GinIndex(fields=['quality_flags'], name='ad_quality_gin'),
        ),
        migrations.AddField(
            model_name='ingestreject',
            name='fetch_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejects', to='core.fetchrun'),
        ),
        migrations.AddField(
            model_name='pagecoverage',
            name='fetch_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_coverages', to='core.fetchrun'),
        ),
        migrations.AddIndex(
            model_name='ingestreject',
            index=models.Index(fields=['rule', 'observed_at'], name='reject_rule_time_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecoverage',
            index=models.Index(fields=['rank_lo', 'fetched_at'], name='pagecov_rank_time_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecoverage',
            index=models.Index(fields=['fetched_at'], name='pagecov_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagecoverage',
            constraint=models.UniqueConstraint(fields=('fetch_run', 'page_index'), name='uq_pagecov_run_page'),
        ),
    ]
