# Generated by Django 5.2.16 on 2026-08-07 21:23

from django.db import migrations, models


def purge_mixed_calendar_snapshots(apps, schema_editor):
    """Drop every pre-rename DailyInventorySnapshot row.

    Those rows were keyed on the raw ``Ad.year``, which mixes Jalali and
    Gregorian model years, so each real cohort was split across two rows with
    two wrong medians. They cannot be repaired here — the calendar of a given
    row is not recoverable from the row itself — and they must not survive,
    because the market index chains cohort medians across consecutive days: a
    ``year``-keyed row on one date matched against a ``year_jalali``-keyed row
    on the next would silently compare two different cohorts and emit a
    fabricated return.

    Safe to delete outright: snapshots are derived data. ``daily_snapshot``
    rewrites today's rows on the next worker tick, and the historical days are
    a loss of chart resolution only — no source data lives here.
    """
    apps.get_model("core", "DailyInventorySnapshot").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingestreject_pagecoverage_ad_quality_flags_and_more'),
    ]

    operations = [
        # Purge BEFORE the rename: afterwards these rows are indistinguishable
        # from correctly-keyed ones.
        migrations.RunPython(
            purge_mixed_calendar_snapshots, migrations.RunPython.noop
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('market', 'Whole market'), ('brand', 'Per brand'), ('model', 'Per model')], max_length=16)),
                ('scope_id', models.CharField(blank=True, max_length=160, null=True)),
                ('date', models.DateField()),
                ('index_value', models.FloatField()),
                ('return_pct', models.FloatField(blank=True, null=True)),
                ('cohort_count', models.IntegerField(default=0)),
                ('ad_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_marketindex',
                'ordering': ('scope', 'scope_id', 'date'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='dailyinventorysnapshot',
            name='uq_snapshot_market_date',
        ),
        migrations.RenameField(
            model_name='dailyinventorysnapshot',
            old_name='year',
            new_name='year_jalali',
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed (absent from the last completed sweeps)')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='dailyinventorysnapshot',
            index=models.Index(fields=['model', 'variant', 'year_jalali', 'date'], name='snap_cohort_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyinventorysnapshot',
            constraint=models.UniqueConstraint(fields=('model', 'variant', 'year_jalali', 'date'), name='uq_snapshot_market_date'),
        ),
        migrations.AddIndex(
            model_name='marketindex',
            index=models.Index(fields=['scope', 'scope_id', 'date'], name='idx_scope_date'),
        ),
        migrations.AddConstraint(
            model_name='marketindex',
            constraint=models.UniqueConstraint(fields=('scope', 'scope_id', 'date'), name='uq_index_scope_date'),
        ),
    ]
