# Generated by Django 5.2.16 on 2026-08-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marketindex_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsCache',
        ),
    ]
