# Generated by Django 5.2.16 on 2026-08-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catalog_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceobservation',
            name='quality_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
