# Generated by Django 5.2.16 on 2026-08-08 17:12

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_price_observation_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='cohort_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cohort_flags'], name='ad_cohort_gin'),
        ),
    ]
