# Generated by Django 5.2.16 on 2026-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ad_cohort_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualitySnapshot',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('total_ads', models.IntegerField(default=0)),
                ('active_ads', models.IntegerField(default=0)),
                ('priced_ads', models.IntegerField(default=0)),
                ('flag_counts', models.JSONField(blank=True, default=dict)),
                ('cohort_flag_counts', models.JSONField(blank=True, default=dict)),
                ('null_rates', models.JSONField(blank=True, default=dict)),
                ('distinct_counts', models.JSONField(blank=True, default=dict)),
                ('rejects_today', models.IntegerField(default=0)),
                ('unconfirmed_brands', models.IntegerField(default=0)),
                ('unconfirmed_models', models.IntegerField(default=0)),
                ('price_p10', models.BigIntegerField(blank=True, null=True)),
                ('price_median', models.BigIntegerField(blank=True, null=True)),
                ('price_p90', models.BigIntegerField(blank=True, null=True)),
                ('alarms', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'history_dataqualitysnapshot',
                'ordering': ('-date',),
            },
        ),
    ]
