# Generated by Django 5.2.16 on 2026-08-08 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_data_quality_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped (prerequisite failed)')], db_index=True, max_length=16)),
                ('triggered_by', models.CharField(choices=[('scheduler', 'Scheduled worker'), ('admin', 'Admin endpoint'), ('manual', 'Manual invocation')], default='scheduler', max_length=16)),
                ('attempt', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'history_jobrun',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['name', '-started_at'], name='jobrun_name_time_idx')],
            },
        ),
    ]
