# Generated by Django 5.2.16 on 2026-08-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_job_run'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditRun',
        ),
        migrations.DeleteModel(
            name='PriceStatistics',
        ),
    ]
