# Generated by Django 5.2.16 on 2026-08-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_drop_dead_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='adversion',
            name='semantic_hash_version',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
