# Generated by Django 5.2.16 on 2026-08-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_semantic_hash_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='image_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='seller_authenticated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='source_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
