# Generated by Django 5.2.16 on 2026-08-09 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ad_presentation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('method', models.CharField(choices=[('image_asset', 'Shared image asset path')], default='image_asset', max_length=24)),
                ('algorithm_version', models.IntegerField(default=1)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'history_vehicleidentity',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_price', models.BigIntegerField(blank=True, null=True)),
                ('last_price', models.BigIntegerField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.ad')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='core.vehicleidentity')),
            ],
            options={
                'db_table': 'history_listingepisode',
                'ordering': ('ad', 'started_at'),
                'indexes': [models.Index(fields=['identity', 'started_at'], name='episode_ident_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('ad',), name='uq_episode_one_open_per_ad')],
            },
        ),
    ]
