# Generated by Django 5.2.16 on 2026-08-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_listing_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ad',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ad',
            name='primary_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        # Django drops column DEFAULTs after AddField; keep durable DB defaults so
        # a mid-migration worker INSERT cannot NotNullViolation on these columns.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE catalog_ad ALTER COLUMN description SET DEFAULT ''",
                "ALTER TABLE catalog_ad ALTER COLUMN primary_image_url SET DEFAULT ''",
                "ALTER TABLE catalog_ad ALTER COLUMN image_urls SET DEFAULT '[]'::jsonb",
            ],
            reverse_sql=[
                "ALTER TABLE catalog_ad ALTER COLUMN description DROP DEFAULT",
                "ALTER TABLE catalog_ad ALTER COLUMN primary_image_url DROP DEFAULT",
                "ALTER TABLE catalog_ad ALTER COLUMN image_urls DROP DEFAULT",
            ],
        ),
    ]
