# Generated by Django 5.2.16 on 2026-08-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_frontend_rebuild"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataQualitySnapshot",
        ),
        migrations.RemoveIndex(
            model_name="listingepisode",
            name="episode_ident_idx",
        ),
        migrations.RemoveField(
            model_name="listingepisode",
            name="identity",
        ),
        migrations.RemoveField(
            model_name="unknowntimephrase",
            name="first_fetch_run",
        ),
        migrations.RemoveField(
            model_name="unknowntimephrase",
            name="last_fetch_run",
        ),
        migrations.DeleteModel(
            name="UnknownTimePhrase",
        ),
        migrations.DeleteModel(
            name="VehicleIdentity",
        ),
    ]
