# Generated by Django 5.2.17 on 2026-08-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_drop_identity_and_quality_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifiedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('discount_pct', models.FloatField(blank=True, null=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notified', to='core.ad')),
            ],
            options={
                'db_table': 'analytics_notifiedad',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='NotifierSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('min_discount_pct', models.FloatField(default=20.0)),
                ('min_peers', models.PositiveIntegerField(default=15)),
                ('price_min', models.BigIntegerField(blank=True, null=True)),
                ('price_max', models.BigIntegerField(blank=True, null=True)),
                ('model_ids', models.JSONField(blank=True, default=list)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'notifier settings',
                'db_table': 'analytics_notifiersettings',
            },
        ),
        migrations.RemoveField(
            model_name='adchangeevent',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='adchangeevent',
            name='new_version',
        ),
        migrations.RemoveField(
            model_name='adchangeevent',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='adchangeevent',
            name='previous_version',
        ),
        migrations.DeleteModel(
            name='MarketSnapshot',
        ),
        migrations.DeleteModel(
            name='AdChangeEvent',
        ),
    ]
