# Generated by Django 5.2.17 on 2026-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notifiedad_notifiersettings_remove_adchangeevent_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchrun',
            name='stop_reason',
            field=models.CharField(blank=True, choices=[('end_of_feed', 'Reached the empty page past the last ad'), ('stale_pages', 'Consecutive pages with nothing new'), ('max_ads', 'Hit the max_ads cap'), ('max_pages', 'Hit the page-range end (backfill)'), ('error', 'Aborted on an unrecoverable error'), ('interrupted', 'Interrupted by the operator'), ('blocked', "Refused by the source's WAF/CDN (403)")], max_length=24),
        ),
    ]
