# Generated by Django 5.2.17 on 2026-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_fetchrun_stop_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(condition=models.Q(('current_price__gt', 0)), fields=['status', 'publish_at'], name='ad_list_active_idx'),
        ),
    ]
