# Generated by Django 5.2.16 on 2026-08-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ad_list_active_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchrun',
            name='feed_end_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
