# Generated by Django 5.2.16 on 2026-08-24 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fetchrun_feed_end_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='likely_reason',
            field=models.CharField(blank=True, choices=[('likely_sold', 'Likely sold'), ('likely_expired', 'Likely expired'), ('reposted', 'Relisted under a new code'), ('unknown', 'Unknown')], db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='ad',
            name='listing_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ad',
            name='reason_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=8),
        ),
        migrations.AddField(
            model_name='ad',
            name='reposted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='core.ad'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Delisted (absent from two complete sweeps)'), ('unverified', 'Unverified (not seen, coverage incomplete)')], db_index=True, default='active', max_length=16),
        ),
    ]
