# Generated by Django 5.2.17 on 2026-08-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_index_coverage_and_brand_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealscorecache',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
