# Generated by Django 5.2.17 on 2026-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_deal_score_needs_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketindex',
            name='scope',
            field=models.CharField(choices=[('market', 'Whole market'), ('brand', 'Per brand'), ('model', 'Per model'), ('price_band', 'Per price band'), ('year_band', 'Per age band'), ('body_type', 'Per body type')], max_length=16),
        ),
    ]
