# Generated by Django 5.2.17 on 2026-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_marketindex_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='excluded_from_analytics',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
