# Generated by Django 5.2.16 on 2026-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_ad_excluded_from_analytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fetchrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("live_fetch", "Live fetch"),
                    ("sold_probe", "Sold probe"),
                    ("bulk_import", "Bulk import"),
                    ("history_replay", "History replay"),
                    ("legacy_baseline", "Legacy baseline"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="bulk_import",
                max_length=32,
            ),
        ),
    ]
