# Generated by Django 5.2.16 on 2026-09-03 13:21

import django.contrib.postgres.indexes
import django.db.models.expressions
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


def backfill_search_text(apps, schema_editor):
    from apps.core.normalization import search_document

    Ad = apps.get_model("core", "Ad")
    batch = []
    for ad in Ad.objects.select_related("brand", "model").iterator(chunk_size=500):
        ad.search_text = search_document(
            ad.title, ad.model.name_fa if ad.model_id else "",
            ad.brand.name_fa if ad.brand_id else "", ad.description,
        )
        batch.append(ad)
        if len(batch) == 500:
            Ad.objects.bulk_update(batch, ["search_text"], batch_size=500)
            batch.clear()
    if batch:
        Ad.objects.bulk_update(batch, ["search_text"], batch_size=500)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("core", "0029_alter_fetchrun_source"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name="ad",
            name="has_high_outlier",
            field=models.GeneratedField(
                db_index=True, db_persist=True,
                expression=django.db.models.expressions.RawSQL(
                    "cohort_flags ? 'price_outlier_high'", [], output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="has_low_outlier",
            field=models.GeneratedField(
                db_index=True, db_persist=True,
                expression=django.db.models.expressions.RawSQL(
                    "cohort_flags ? 'price_outlier_low'", [], output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="is_verified",
            field=models.GeneratedField(
                db_index=True, db_persist=True,
                expression=django.db.models.expressions.RawSQL(
                    "NOT (excluded_from_analytics OR quality_flags ?| ARRAY["
                    "'brand_missing', 'code_missing', 'photo_missing', "
                    "'price_missing_for_lumpsum', 'price_too_low'])",
                    [], output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="ad", name="search_text", field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(backfill_search_text, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="ad",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_text"], name="ad_search_text_trgm", opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                condition=models.Q(
                    ("current_price__gt", 0), ("is_verified", True),
                    ("price_basis_unclear", False),
                ),
                fields=["status", "publish_at"], name="ad_scorable_idx",
            ),
        ),
    ]
