# Generated by Django 5.2.17 on 2026-09-28 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_enable_operator_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedImage',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=160, unique=True)),
                ('content_type', models.CharField(max_length=32)),
                ('byte_size', models.PositiveIntegerField()),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('backed_up_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_archivedimage',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='admission_state',
            field=models.CharField(choices=[('legacy_unverified', 'Legacy photo evidence unverified'), ('pending', 'Waiting for image and classification evidence'), ('ready', 'Catalog ready'), ('history_only', 'Qualified history only'), ('rejected', 'Rejected from catalog')], db_index=True, default='legacy_unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_ads', to='core.adversion'),
        ),
        migrations.AddField(
            model_name='adversion',
            name='classification_rule',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='adversion',
            name='classification_state',
            field=models.CharField(db_index=True, default='needs_review', max_length=16),
        ),
        migrations.AddField(
            model_name='adversion',
            name='classified_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classified_versions', to='core.model'),
        ),
        migrations.AddField(
            model_name='adversion',
            name='classified_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classified_versions', to='core.variant'),
        ),
        migrations.CreateModel(
            name='DetailPageCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('outcome', models.CharField(choices=[('available', 'Page available'), ('unavailable', 'Source says page unavailable'), ('blocked', 'Source blocked the check'), ('error', 'Check failed')], db_index=True, max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_checks', to='core.ad')),
                ('fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_checks', to='core.fetchrun')),
            ],
            options={
                'db_table': 'history_detailpagecheck',
                'ordering': ('-checked_at',),
            },
        ),
        migrations.CreateModel(
            name='SourceModelAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_family', models.CharField(max_length=160, unique=True)),
                ('reviewed', models.BooleanField(db_index=True, default=False)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_aliases', to='core.model')),
            ],
            options={
                'db_table': 'catalog_sourcemodelalias',
            },
        ),
        migrations.CreateModel(
            name='AdVersionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('source_url', models.URLField(max_length=500)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified archive'), ('blocked', 'Source blocked'), ('failed', 'Retrieval failed')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.adversion')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_uses', to='core.archivedimage')),
            ],
            options={
                'db_table': 'history_adversionphoto',
                'constraints': [models.UniqueConstraint(fields=('version', 'position'), name='uq_version_photo_position')],
            },
        ),
    ]
