# Generated by Django 5.2.17 on 2026-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_archivedimage_ad_admission_state_ad_current_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='detail_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='detail_state',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='ad',
            name='source_family',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
    ]
