# Generated by Django 5.2.17 on 2026-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_ad_detail_checked_at_ad_detail_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adversionphoto',
            name='pause_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
