# Generated by Django 5.2.17 on 2026-09-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_adversionphoto_pause_started_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceModelAlias',
        ),
    ]
