# Generated by Django 5.2.17 on 2026-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_drop_sourcemodelalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='image_dead_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
