# Generated by Django 5.2.17 on 2026-09-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_alter_marketindex_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('price', 'Quantile price model (p10/p50/p90)'), ('sell_fast', 'Probability of leaving the feed quickly'), ('anomaly', 'Isolation Forest over the feature space'), ('model_text', 'Ad text to catalogue model'), ('value_tier', 'Per-variant value tiers')], db_index=True, max_length=32)),
                ('version', models.IntegerField()),
                ('algorithm', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('shadow', 'Shadow — scored but not served'), ('active', 'Active — served'), ('retired', 'Retired — superseded or rolled back')], db_index=True, default='shadow', max_length=16)),
                ('trained_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('training_rows', models.IntegerField(default=0)),
                ('trained_through', models.DateTimeField(blank=True, null=True)),
                ('feature_spec', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('artifact_path', models.CharField(blank=True, max_length=400)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ml_model',
                'ordering': ('name', '-version'),
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uq_mlmodel_name_version'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('name',), name='uq_mlmodel_one_active_per_name')],
            },
        ),
        migrations.CreateModel(
            name='AdPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_p10', models.BigIntegerField(blank=True, null=True)),
                ('price_p50', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('price_p90', models.BigIntegerField(blank=True, null=True)),
                ('residual_pct', models.FloatField(blank=True, db_index=True, null=True)),
                ('contributions', models.JSONField(blank=True, default=list)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('anomaly_kind', models.CharField(blank=True, choices=[('underpriced_candidate', 'Below predicted p10, features unremarkable'), ('data_anomaly', 'Outlier in feature space — suspect the record')], db_index=True, max_length=32)),
                ('sell_fast_prob', models.FloatField(blank=True, null=True)),
                ('sell_fast_horizon_days', models.IntegerField(blank=True, null=True)),
                ('value_tier', models.CharField(blank=True, db_index=True, max_length=32)),
                ('value_tier_rank', models.IntegerField(blank=True, null=True)),
                ('suspected_model_prob', models.FloatField(blank=True, null=True)),
                ('model_versions', models.JSONField(blank=True, default=dict)),
                ('scored_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml', to='core.ad')),
                ('suspected_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_suspected_ads', to='core.model')),
            ],
            options={
                'db_table': 'ml_adprediction',
                'indexes': [models.Index(fields=['anomaly_kind', '-residual_pct'], name='mlpred_band_idx')],
            },
        ),
    ]
