# Generated by Django 5.2.17 on 2026-09-02 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ad_excluded_from_analytics'),
        ('ml', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('suspect_model', 'Filed under the wrong model'), ('data_anomaly', 'The record itself looks broken')], max_length=32)),
                ('verdict', models.CharField(choices=[('confirmed', 'The model was right'), ('rejected', 'The model was wrong')], max_length=16)),
                ('claim', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='core.ad')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_reviewdecision',
                'constraints': [models.UniqueConstraint(fields=('ad', 'kind'), name='one_decision_per_flag')],
            },
        ),
    ]
