# Generated by Django 5.2.16 on 2026-07-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('payment', models.BigIntegerField(blank=True, null=True)),
                ('prepayment', models.BigIntegerField(blank=True, null=True)),
                ('installments', models.IntegerField(blank=True, null=True)),
                ('price_type', models.CharField(blank=True, max_length=64)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='catalog.ad')),
                ('fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='history.fetchrun')),
            ],
            options={
                'db_table': 'market_priceobservation',
                'ordering': ('observed_at',),
                'indexes': [models.Index(fields=['ad', 'observed_at'], name='po_ad_time_idx')],
            },
        ),
    ]
