# Generated by Django 5.2.16 on 2026-07-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ad_removed_at_ad_status'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDropEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.BigIntegerField(blank=True, null=True)),
                ('new_price', models.BigIntegerField(blank=True, null=True)),
                ('drop_amount', models.BigIntegerField(db_index=True, default=0)),
                ('drop_pct', models.FloatField(db_index=True, default=0.0)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_drops', to='catalog.ad')),
            ],
            options={
                'db_table': 'market_pricedropevent',
                'ordering': ('-observed_at',),
                'indexes': [models.Index(fields=['ad', '-observed_at'], name='pde_ad_time_idx'), models.Index(fields=['-drop_pct'], name='pde_drop_pct_idx')],
            },
        ),
    ]
